language: ruby
rvm:
  - 2.6.5
cache:
  - bundler
  - yarn
services:
  - mysql
before_install:
  - cp config/database.yml.travis config/database.yml  
before_script:  
  - bundle install --jobs=3 --retry=3
  - yarn
  - RAILS_ENV=test bundle exec rails generate devise:install --skip --quite
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
script:
  - bundle exec rake test
  # - bundle exec rake test:system