language: ruby
rvm:
  - 2.6.5
cache:
  - bundler
  - yarn
addons:
  mariadb: '10.1'
before_install:
  - cp config/database.yml.travis config/database.yml
  - sudo mysql -e 'CREATE DATABASE gift_box_test;'
before_script:  
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  - bundle exec rake test
  # - bundle exec rake test:system